{{--
    Everything a crawler or a link preview needs.

    The multilingual half matters as much as the tags themselves: each page
    declares a canonical for itself, an hreflang for all four translations
    including itself (reciprocity is what makes Google trust the cluster), and
    an x-default for readers whose language is not one of ours.
--}}
@php
    // Title and description are per page and per locale, so they are keyed by
    // the route name: `meta.home.title`, `meta.v3.title`. A new page that
    // forgets its block fails the build here rather than shipping a blank head.
    $title = $page->t("meta.{$page->page}.title");
    $description = $page->t("meta.{$page->page}.description");
    $canonical = $page->absolute($page->localePath($page->page));
    $alternates = $page->alternates();

    // One card per locale, so a link shared in French previews in French.
    // 1200x630, generated by `npm run og`.
    $ogImage = $page->absolute("/og/monica-{$page->locale}.png");

    $structuredData = [
        '@context' => 'https://schema.org',
        '@graph' => [
            [
                '@type' => 'Organization',
                '@id' => $page->absolute('/#organization'),
                'name' => 'Monica',
                'url' => $page->absolute('/'),
                'logo' => $page->absolute('/assets/images/monica-panda-mark.jpg'),
                'sameAs' => [$page->links['github']],
            ],
            [
                '@type' => 'WebSite',
                '@id' => $page->absolute('/#website'),
                'name' => 'Monica',
                'url' => $page->absolute('/'),
                'description' => $description,
                'inLanguage' => $page->locale,
                'publisher' => ['@id' => $page->absolute('/#organization')],
            ],
        ],
    ];
@endphp

<title>{{ $title }}</title>
<meta name="description" content="{{ $description }}">
<link rel="canonical" href="{{ $canonical }}">

{{-- Allow full-size image previews and untruncated snippets in search results. --}}
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">

@foreach ($alternates as $alternate)
    <link rel="alternate" hreflang="{{ $alternate['locale'] }}" href="{{ $alternate['absolute'] }}">
@endforeach
<link rel="alternate" hreflang="x-default" href="{{ $page->absolute($page->localePath($page->page, $page->defaultLocale)) }}">

<meta property="og:type" content="website">
<meta property="og:site_name" content="Monica">
<meta property="og:title" content="{{ $title }}">
<meta property="og:description" content="{{ $description }}">
<meta property="og:url" content="{{ $canonical }}">
<meta property="og:locale" content="{{ $page->ogLocales[$page->locale] }}">
@foreach ($alternates as $alternate)
    @continue($alternate['locale'] === $page->locale)
    <meta property="og:locale:alternate" content="{{ $page->ogLocales[$alternate['locale']] }}">
@endforeach
<meta property="og:image" content="{{ $ogImage }}">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="{{ $page->t('meta.imageAlt') }}">

{{-- X and Slack read og:title, og:description and og:image directly. The card
     type has no Open Graph equivalent, so it has to be stated. --}}
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image:alt" content="{{ $page->t('meta.imageAlt') }}">

<script type="application/ld+json">{!! json_encode($structuredData, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) !!}</script>
