{{--
    Everything a crawler or a link preview needs.

    The multilingual half matters as much as the tags themselves: each page
    declares a canonical for itself, an hreflang for every translation
    including itself (reciprocity is what makes Google trust the cluster), and
    an x-default for readers whose language is not one of ours.
--}}
@php
    // Title and description are per page and per locale, so they are keyed by
    // the route name: `meta.home.title`, `meta.v3.title`. A new page that
    // forgets its block fails the build here rather than shipping a blank head.
    //
    // A post is the exception: its title and description are the post's own, in
    // the language it was written in, so there is nothing in lang/ to look up.
    $isPost = $page->page === 'post';

    if ($isPost) {
        $title = $page->t('meta.post.title', [':title' => $page->title]);
        $description = $page->description;
    } else {
        $title = $page->t("meta.{$page->page}.title");
        $description = $page->t("meta.{$page->page}.description");
    }

    // Jigsaw hands a paginated template its current page as a view variable.
    // `$page->pagination` is a different thing — the front-matter block that
    // asked for pagination in the first place — so it is deliberately not what
    // is read here.
    $number = isset($pagination) ? $pagination->currentPage : 1;

    // Page 2 of a list is not the list. Saying so keeps four pages of the blog
    // from competing for the same result with the same title.
    if ($number > 1) {
        $title = $page->t('meta.paginated', [
            ':title' => $title,
            ':page' => $number,
            ':total' => $pagination->totalPages,
        ]);
    }

    $canonical = $page->absolute($page->canonicalPath(null, $number));
    $alternates = $page->alternates(null, $number);

    // One card per locale, so a link shared in French previews in French.
    // 1200x630, generated by `npm run og`.
    $ogImage = $page->absolute("/og/monica-{$page->locale}.png");

    // ------------------------------------------------------- structured data

    /**
     * One graph per page, cross-referenced by @id rather than repeated.
     *
     * The two site-wide nodes keep a fixed @id on every page of every locale,
     * so a crawler reading fifty pages sees one Organization and one WebSite
     * rather than fifty of each. Everything below them is per page and hangs
     * its @id off the canonical, which is unique by construction.
     */
    $organization = $page->absolute('/#organization');
    $website = $page->absolute('/#website');
    $software = $page->absolute('/#software');
    $webPage = $canonical . '#webpage';
    $breadcrumb = $canonical . '#breadcrumb';

    /**
     * Where this page sits in the site, ending with the page itself.
     *
     * The homepage gets no trail: a one-item breadcrumb states that the root
     * is the root. Everything else starts there and adds what its URL already
     * says, so /en/features/dashboard/ reads Home, Features, Powerful
     * dashboard, in that order.
     */
    $trail = [];

    if ($page->page !== 'home') {
        $trail[] = ['name' => $page->t('meta.breadcrumb.home'), 'path' => $page->localePath('home')];

        if ($isPost) {
            $trail[] = ['name' => $page->t('meta.breadcrumb.blog'), 'path' => $page->blogPath()];
            $trail[] = ['name' => $page->title, 'path' => $page->postPath($page->slug)];
        } elseif ($page->page === 'blog') {
            $trail[] = ['name' => $page->t('meta.breadcrumb.blog'), 'path' => $page->blogPath()];

            // Page 2 is a page of the list, not the list, which is the same
            // distinction the title and the canonical already make.
            if ($number > 1) {
                $trail[] = [
                    'name' => $page->t('meta.breadcrumb.page', [':number' => $number]),
                    'path' => $page->blogPath(null, $number),
                ];
            }
        } else {
            // The two other feature tabs are nested under /features/, so the
            // section they belong to is a crumb in its own right.
            if (in_array($page->page, ['featuresDashboard', 'featuresJournal'], true)) {
                $trail[] = ['name' => $page->t('meta.breadcrumb.features'), 'path' => $page->localePath('features')];
            }

            $trail[] = [
                'name' => $page->t("meta.breadcrumb.{$page->page}"),
                'path' => $page->localePath($page->page),
            ];
        }
    }

    /**
     * What kind of page this is, where schema.org has a word for it. The blog
     * index is a list of other pages and the team page is about the people
     * behind the product; everything else is an ordinary WebPage, including a
     * post, which carries its BlogPosting as a separate node.
     */
    $webPageType = ['blog' => 'CollectionPage', 'team' => 'AboutPage'][$page->page] ?? 'WebPage';

    $structuredData = [
        '@context' => 'https://schema.org',
        '@graph' => [
            [
                '@type' => 'Organization',
                '@id' => $organization,
                'name' => 'Monica',
                'url' => $page->absolute('/'),
                'logo' => $page->absolute('/assets/images/monica-panda-mark.jpg'),
                'sameAs' => [$page->links['github']],
            ],
            [
                '@type' => 'WebSite',
                '@id' => $website,
                'name' => 'Monica',
                'url' => $page->absolute('/'),

                // The site's description, not the page's. This node has one
                // @id across the whole site, so letting the current page fill
                // it in would describe the same thing fifty different ways.
                'description' => $page->t('meta.home.description'),
                'inLanguage' => $page->locale,
                'publisher' => ['@id' => $organization],
            ],
            array_filter([
                '@type' => $webPageType,
                '@id' => $webPage,
                'url' => $canonical,
                'name' => $title,
                'description' => $description,
                'inLanguage' => $page->locale,
                'isPartOf' => ['@id' => $website],
                'breadcrumb' => count($trail) > 1 ? ['@id' => $breadcrumb] : null,
                'datePublished' => $isPost ? $page->isoDate() : null,
            ]),
        ],
    ];

    /**
     * A trail of one is the page itself and says nothing, so it is not worth a
     * node. Every crumb keeps its `item`, the last one included: the URL is
     * real, and the dead-link checker reads `item` like any other link.
     */
    if (count($trail) > 1) {
        $structuredData['@graph'][] = [
            '@type' => 'BreadcrumbList',
            '@id' => $breadcrumb,
            'itemListElement' => collect($trail)
                ->values()
                ->map(fn ($crumb, $index) => [
                    '@type' => 'ListItem',
                    'position' => $index + 1,
                    'name' => $crumb['name'],
                    'item' => $page->absolute($crumb['path']),
                ])
                ->all(),
        ];
    }

    /**
     * The product itself, on the two pages that are about buying it.
     *
     * Not on every page: SoftwareApplication describes a thing for sale, and
     * repeating it under a 2017 release note tells a crawler nothing it did
     * not already learn from the homepage. It keeps one @id on both, so the
     * two pages describe one application rather than two.
     *
     * No aggregateRating. We have no review data, and inventing one is the
     * fastest way to a manual action.
     */
    if (in_array($page->page, ['home', 'pricing'], true)) {
        $pricing = $page->absolute($page->localePath('pricing'));
        $currency = $page->plans['currency'];

        // Both hosted prices are subscriptions, so each says what it buys and
        // for how long: a bare `price` of 90 would read as a one-off purchase.
        $subscription = fn (string $name, string $amount, string $unit) => [
            '@type' => 'Offer',
            'name' => $name,
            'price' => $amount,
            'priceCurrency' => $currency,
            'url' => $pricing,
            'availability' => 'https://schema.org/InStock',
            'priceSpecification' => [
                '@type' => 'UnitPriceSpecification',
                'price' => $amount,
                'priceCurrency' => $currency,
                'referenceQuantity' => [
                    '@type' => 'QuantitativeValue',
                    'value' => 1,

                    // UN/CEFACT codes: MON is a month, ANN a year.
                    'unitCode' => $unit,
                ],
            ],
        ];

        $structuredData['@graph'][] = [
            '@type' => 'SoftwareApplication',
            '@id' => $software,
            'name' => 'Monica',
            'url' => $page->absolute('/'),
            'description' => $page->t('meta.home.description'),

            // schema.org's vocabulary has no "personal CRM", and the closest
            // term it does have is the one Google's own examples use for this
            // kind of product.
            'applicationCategory' => 'BusinessApplication',
            'operatingSystem' => 'Web',
            'inLanguage' => $page->locales,
            'publisher' => ['@id' => $organization],

            // True because of the self-hosted offer below: the application is
            // free, and the hosted service is what costs money.
            'isAccessibleForFree' => true,
            'license' => 'https://www.gnu.org/licenses/agpl-3.0.html',
            'sameAs' => [$page->links['github']],
            'offers' => [
                $subscription($page->t('meta.software.monthly'), $page->plans['monthly'], 'MON'),
                $subscription($page->t('meta.software.yearly'), $page->plans['yearly'], 'ANN'),
                [
                    '@type' => 'Offer',
                    'name' => $page->t('meta.software.selfHosted'),
                    'price' => $page->plans['selfHosted'],
                    'priceCurrency' => $currency,
                    'url' => $pricing,
                    'availability' => 'https://schema.org/InStock',
                ],
            ],
        ];
    }

    /**
     * A post says what it is, when it was written and who by. The body is
     * translated, so `inLanguage` is the page's locale: the German page is a
     * German article, not an English one with German chrome.
     */
    if ($isPost) {
        $structuredData['@graph'][] = [
            '@type' => 'BlogPosting',
            '@id' => $canonical . '#post',
            'mainEntityOfPage' => ['@id' => $webPage],
            'isPartOf' => ['@id' => $webPage],
            'headline' => $page->title,
            'description' => $description,
            'datePublished' => $page->isoDate(),
            'inLanguage' => $page->locale,
            'author' => ['@type' => 'Person', 'name' => $page->author],
            'publisher' => ['@id' => $organization],
        ];
    }
@endphp

<title>{{ $title }}</title>
<meta name="description" content="{{ $description }}">
<link rel="canonical" href="{{ $canonical }}">

{{-- Allow full-size image previews and untruncated snippets in search results. --}}
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">

@foreach ($alternates as $alternate)
    <link rel="alternate" hreflang="{{ $alternate['locale'] }}" href="{{ $alternate['absolute'] }}">
@endforeach
<link rel="alternate" hreflang="x-default" href="{{ $page->absolute($page->canonicalPath($page->defaultLocale, $number)) }}">

<meta property="og:type" content="{{ $isPost ? 'article' : 'website' }}">
@if ($isPost)
    <meta property="article:published_time" content="{{ $page->isoDate() }}">
    <meta property="article:author" content="{{ $page->author }}">
@endif
<meta property="og:site_name" content="Monica">
<meta property="og:title" content="{{ $title }}">
<meta property="og:description" content="{{ $description }}">
<meta property="og:url" content="{{ $canonical }}">
<meta property="og:locale" content="{{ $page->ogLocales[$page->locale] }}">
@foreach ($alternates as $alternate)
    @continue($alternate['locale'] === $page->locale)
    <meta property="og:locale:alternate" content="{{ $page->ogLocales[$alternate['locale']] }}">
@endforeach
<meta property="og:image" content="{{ $ogImage }}">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="{{ $page->t('meta.imageAlt') }}">

{{-- X and Slack read og:title, og:description and og:image directly. The card
     type has no Open Graph equivalent, so it has to be stated. --}}
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image:alt" content="{{ $page->t('meta.imageAlt') }}">

<script type="application/ld+json">{!! json_encode($structuredData, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) !!}</script>
